source "https://rubygems.org"

# GitHub Pages gem includes Jekyll and all GitHub Pages dependencies
gem "github-pages", group: :jekyll_plugins

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :mswin]

# HTTP server for local testing
gem "webrick"